# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from novatel_oem7_msgs/InertialSolutionStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class InertialSolutionStatus(genpy.Message):
  _md5sum = "e6e451c61d52151bd82b333d8be963d5"
  _type = "novatel_oem7_msgs/InertialSolutionStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """
uint32 INS_INACTIVE            =  0
uint32 INS_ALIGNING            =  1
uint32 INS_HIGH_VARIANCE       =  2
uint32 INS_SOLUTION_GOOD       =  3
uint32 INS_SOLUTION_FREE       =  6
uint32 INS_ALIGNMENT_COMPLETE  =  7
uint32 DETERMINING_ORIENTATION =  8
uint32 WAITING_INITIAL_POS     =  9
uint32 WAITING_AZIMUTH         = 10
uint32 INITIALIZING_BIASES     = 11
uint32 MOTION_DETECT           = 12

uint32 status"""
  # Pseudo-constants
  INS_INACTIVE = 0
  INS_ALIGNING = 1
  INS_HIGH_VARIANCE = 2
  INS_SOLUTION_GOOD = 3
  INS_SOLUTION_FREE = 6
  INS_ALIGNMENT_COMPLETE = 7
  DETERMINING_ORIENTATION = 8
  WAITING_INITIAL_POS = 9
  WAITING_AZIMUTH = 10
  INITIALIZING_BIASES = 11
  MOTION_DETECT = 12

  __slots__ = ['status']
  _slot_types = ['uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       status

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(InertialSolutionStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.status is None:
        self.status = 0
    else:
      self.status = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.status
      buff.write(_get_struct_I().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (self.status,) = _get_struct_I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.status
      buff.write(_get_struct_I().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (self.status,) = _get_struct_I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
