# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from novatel_oem7_msgs/Rotation.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import novatel_oem7_msgs.msg

class Rotation(genpy.Message):
  _md5sum = "d5326fc395098838339ff2dec1eb5cd5"
  _type = "novatel_oem7_msgs/Rotation"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """RotationalOffset    rotation
INSFrame            frame
float32             x_rotation
float32             y_rotation
float32             z_rotation
float32             x_rotation_stdev
float32             y_rotation_stdev
float32             z_rotation_stdev
INSSourceStatus     rotation_source
================================================================================
MSG: novatel_oem7_msgs/RotationalOffset
uint32 USER 	=  4
uint32 MARK1 	=  5
uint32 MARK2    =  6
uint32 ALIGN    =  8
uint32 MARK3    =  9
uint32 MARK4    = 10
uint32 RBV      = 11
uint32 RBM      = 12

uint32 offset
================================================================================
MSG: novatel_oem7_msgs/INSFrame
uint32 IMUBODY = 0
uint32 VEHICLE = 1

uint32 frame
================================================================================
MSG: novatel_oem7_msgs/INSSourceStatus
uint32 FROM_NVM           = 1
uint32 CALIBRATING        = 2
uint32 CALIBRATED         = 3
uint32 FROM_COMMAND       = 4
uint32 RESET              = 5
uint32 FROM_DUAL_ANT      = 6
uint32 INS_CONVERSING     = 7
uint32 INSUFFICIENT_SPEED = 8
uint32 HIGH_ROTATION      = 9

uint32 status"""
  __slots__ = ['rotation','frame','x_rotation','y_rotation','z_rotation','x_rotation_stdev','y_rotation_stdev','z_rotation_stdev','rotation_source']
  _slot_types = ['novatel_oem7_msgs/RotationalOffset','novatel_oem7_msgs/INSFrame','float32','float32','float32','float32','float32','float32','novatel_oem7_msgs/INSSourceStatus']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       rotation,frame,x_rotation,y_rotation,z_rotation,x_rotation_stdev,y_rotation_stdev,z_rotation_stdev,rotation_source

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Rotation, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.rotation is None:
        self.rotation = novatel_oem7_msgs.msg.RotationalOffset()
      if self.frame is None:
        self.frame = novatel_oem7_msgs.msg.INSFrame()
      if self.x_rotation is None:
        self.x_rotation = 0.
      if self.y_rotation is None:
        self.y_rotation = 0.
      if self.z_rotation is None:
        self.z_rotation = 0.
      if self.x_rotation_stdev is None:
        self.x_rotation_stdev = 0.
      if self.y_rotation_stdev is None:
        self.y_rotation_stdev = 0.
      if self.z_rotation_stdev is None:
        self.z_rotation_stdev = 0.
      if self.rotation_source is None:
        self.rotation_source = novatel_oem7_msgs.msg.INSSourceStatus()
    else:
      self.rotation = novatel_oem7_msgs.msg.RotationalOffset()
      self.frame = novatel_oem7_msgs.msg.INSFrame()
      self.x_rotation = 0.
      self.y_rotation = 0.
      self.z_rotation = 0.
      self.x_rotation_stdev = 0.
      self.y_rotation_stdev = 0.
      self.z_rotation_stdev = 0.
      self.rotation_source = novatel_oem7_msgs.msg.INSSourceStatus()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I6fI().pack(_x.rotation.offset, _x.frame.frame, _x.x_rotation, _x.y_rotation, _x.z_rotation, _x.x_rotation_stdev, _x.y_rotation_stdev, _x.z_rotation_stdev, _x.rotation_source.status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.rotation is None:
        self.rotation = novatel_oem7_msgs.msg.RotationalOffset()
      if self.frame is None:
        self.frame = novatel_oem7_msgs.msg.INSFrame()
      if self.rotation_source is None:
        self.rotation_source = novatel_oem7_msgs.msg.INSSourceStatus()
      end = 0
      _x = self
      start = end
      end += 36
      (_x.rotation.offset, _x.frame.frame, _x.x_rotation, _x.y_rotation, _x.z_rotation, _x.x_rotation_stdev, _x.y_rotation_stdev, _x.z_rotation_stdev, _x.rotation_source.status,) = _get_struct_2I6fI().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I6fI().pack(_x.rotation.offset, _x.frame.frame, _x.x_rotation, _x.y_rotation, _x.z_rotation, _x.x_rotation_stdev, _x.y_rotation_stdev, _x.z_rotation_stdev, _x.rotation_source.status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.rotation is None:
        self.rotation = novatel_oem7_msgs.msg.RotationalOffset()
      if self.frame is None:
        self.frame = novatel_oem7_msgs.msg.INSFrame()
      if self.rotation_source is None:
        self.rotation_source = novatel_oem7_msgs.msg.INSSourceStatus()
      end = 0
      _x = self
      start = end
      end += 36
      (_x.rotation.offset, _x.frame.frame, _x.x_rotation, _x.y_rotation, _x.z_rotation, _x.x_rotation_stdev, _x.y_rotation_stdev, _x.z_rotation_stdev, _x.rotation_source.status,) = _get_struct_2I6fI().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I6fI = None
def _get_struct_2I6fI():
    global _struct_2I6fI
    if _struct_2I6fI is None:
        _struct_2I6fI = struct.Struct("<2I6fI")
    return _struct_2I6fI
