(cl:in-package novatel_oem7_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          NOV_HEADER-VAL
          NOV_HEADER
          SOL_STATUS-VAL
          SOL_STATUS
          POS_TYPE-VAL
          POS_TYPE
          LON_ZONE_NUMBER-VAL
          LON_ZONE_NUMBER
          LAT_ZONE_LETTER-VAL
          LAT_ZONE_LETTER
          NORTHING-VAL
          NORTHING
          EASTING-VAL
          EASTING
          HEIGHT-VAL
          HEIGHT
          UNDULATION-VAL
          UNDULATION
          DATUM_ID-VAL
          DATUM_ID
          NORTHING_STDDEV-VAL
          NORTHING_STDDEV
          EASTING_STDDEV-VAL
          EASTING_STDDEV
          HEIGHT_STDDEV-VAL
          HEIGHT_STDDEV
          STN_ID-VAL
          STN_ID
          DIFF_AGE-VAL
          DIFF_AGE
          SOL_AGE-VAL
          SOL_AGE
          NUM_SVS-VAL
          NUM_SVS
          NUM_SOL_SVS-VAL
          NUM_SOL_SVS
          NUM_SOL_GGL1_SVS-VAL
          NUM_SOL_GGL1_SVS
          NUM_SOL_MULTI_SVS-VAL
          NUM_SOL_MULTI_SVS
          RESERVED-VAL
          RESERVED
          EXT_SOL_STAT-VAL
          EXT_SOL_STAT
          GALILEO_BEIDOU_SIG_MASK-VAL
          GALILEO_BEIDOU_SIG_MASK
          GPS_GLONASS_SIG_MASK-VAL
          GPS_GLONASS_SIG_MASK
))