(cl:in-package novatel_oem7_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          NOV_HEADER-VAL
          NOV_HEADER
          SOL_STATUS-VAL
          SOL_STATUS
          POS_TYPE-VAL
          POS_TYPE
          LENGTH-VAL
          LENGTH
          HEADING-VAL
          HEADING
          PITCH-VAL
          PITCH
          RESERVED-VAL
          RESERVED
          HEADING_STDEV-VAL
          HEADING_STDEV
          PITCH_STDEV-VAL
          PITCH_STDEV
          ROVER_STN_ID-VAL
          ROVER_STN_ID
          MASTER_STN_ID-VAL
          MASTER_STN_ID
          NUM_SV_TRACKED-VAL
          NUM_SV_TRACKED
          NUM_SV_IN_SOL-VAL
          NUM_SV_IN_SOL
          NUM_SV_OBS-VAL
          NUM_SV_OBS
          NUM_SV_MULTI-VAL
          NUM_SV_MULTI
          SOL_SOURCE-VAL
          SOL_SOURCE
          EXT_SOL_STATUS-VAL
          EXT_SOL_STATUS
          GALILEO_BEIDOU_SIG_MASK-VAL
          GALILEO_BEIDOU_SIG_MASK
          GPS_GLONASS_SIG_MASK-VAL
          GPS_GLONASS_SIG_MASK
))