(cl:in-package novatel_oem7_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          NOV_HEADER-VAL
          NOV_HEADER
          ERROR-VAL
          ERROR
          NUM_STATUS_CODES-VAL
          NUM_STATUS_CODES
          RXSTAT-VAL
          RXSTAT
          RXSTAT_PRI_MASK-VAL
          RXSTAT_PRI_MASK
          RXSTAT_SET_MASK-VAL
          RXSTAT_SET_MASK
          RXSTAT_CLR_MASK-VAL
          RXSTAT_CLR_MASK
          AUX1_STAT-VAL
          AUX1_STAT
          AUX1_STAT_PRI-VAL
          AUX1_STAT_PRI
          AUX1_STAT_SET-VAL
          AUX1_STAT_SET
          AUX1_STAT_CLR-VAL
          AUX1_STAT_CLR
          AUX2_STAT-VAL
          AUX2_STAT
          AUX2_STAT_PRI-VAL
          AUX2_STAT_PRI
          AUX2_STAT_SET-VAL
          AUX2_STAT_SET
          AUX2_STAT_CLR-VAL
          AUX2_STAT_CLR
          AUX3_STAT-VAL
          AUX3_STAT
          AUX3_STAT_PRI-VAL
          AUX3_STAT_PRI
          AUX3_STAT_SET-VAL
          AUX3_STAT_SET
          AUX3_STAT_CLR-VAL
          AUX3_STAT_CLR
          AUX4_STAT-VAL
          AUX4_STAT
          AUX4_STAT_PRI-VAL
          AUX4_STAT_PRI
          AUX4_STAT_SET-VAL
          AUX4_STAT_SET
          AUX4_STAT_CLR-VAL
          AUX4_STAT_CLR
          ERROR_BITS-VAL
          ERROR_BITS
          ERROR_STRS-VAL
          ERROR_STRS
          RXSTAT_BITS-VAL
          RXSTAT_BITS
          RXSTAT_STRS-VAL
          RXSTAT_STRS
          AUX1_STAT_BITS-VAL
          AUX1_STAT_BITS
          AUX1_STAT_STRS-VAL
          AUX1_STAT_STRS
          AUX2_STAT_BITS-VAL
          AUX2_STAT_BITS
          AUX2_STAT_STRS-VAL
          AUX2_STAT_STRS
          AUX3_STAT_BITS-VAL
          AUX3_STAT_BITS
          AUX3_STAT_STRS-VAL
          AUX3_STAT_STRS
          AUX4_STAT_BITS-VAL
          AUX4_STAT_BITS
          AUX4_STAT_STRS-VAL
          AUX4_STAT_STRS
))