(cl:in-package novatel_oem7_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          NOV_HEADER-VAL
          NOV_HEADER
          LATITUDE_STDEV-VAL
          LATITUDE_STDEV
          LONGITUDE_STDEV-VAL
          LONGITUDE_STDEV
          HEIGHT_STDEV-VAL
          HEIGHT_STDEV
          NORTH_VELOCITY_STDEV-VAL
          NORTH_VELOCITY_STDEV
          EAST_VELOCITY_STDEV-VAL
          EAST_VELOCITY_STDEV
          UP_VELOCITY_STDEV-VAL
          UP_VELOCITY_STDEV
          ROLL_STDEV-VAL
          ROLL_STDEV
          PITCH_STDEV-VAL
          PITCH_STDEV
          AZIMUTH_STDEV-VAL
          AZIMUTH_STDEV
          EXT_SOL_STATUS-VAL
          EXT_SOL_STATUS
          TIME_SINCE_LAST_UPDATE-VAL
          TIME_SINCE_LAST_UPDATE
          RESERVED1-VAL
          RESERVED1
          RESERVED2-VAL
          RESERVED2
          RESERVED3-VAL
          RESERVED3
))