(cl:in-package novatel_oem7_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          NOV_HEADER-VAL
          NOV_HEADER
          INS_STATUS-VAL
          INS_STATUS
          POS_TYPE-VAL
          POS_TYPE
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          HEIGHT-VAL
          HEIGHT
          UNDULATION-VAL
          UNDULATION
          NORTH_VELOCITY-VAL
          NORTH_VELOCITY
          EAST_VELOCITY-VAL
          EAST_VELOCITY
          UP_VELOCITY-VAL
          UP_VELOCITY
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          AZIMUTH-VAL
          AZIMUTH
          LATITUDE_STDEV-VAL
          LATITUDE_STDEV
          LONGITUDE_STDEV-VAL
          LONGITUDE_STDEV
          HEIGHT_STDEV-VAL
          HEIGHT_STDEV
          NORTH_VELOCITY_STDEV-VAL
          NORTH_VELOCITY_STDEV
          EAST_VELOCITY_STDEV-VAL
          EAST_VELOCITY_STDEV
          UP_VELOCITY_STDEV-VAL
          UP_VELOCITY_STDEV
          ROLL_STDEV-VAL
          ROLL_STDEV
          PITCH_STDEV-VAL
          PITCH_STDEV
          AZIMUTH_STDEV-VAL
          AZIMUTH_STDEV
          EXT_SOL_STATUS-VAL
          EXT_SOL_STATUS
          TIME_SINCE_UPDATE-VAL
          TIME_SINCE_UPDATE
))