// Generated by gencpp from file novatel_oem7_msgs/AccessStatus.msg
// DO NOT EDIT!


#ifndef NOVATEL_OEM7_MSGS_MESSAGE_ACCESSSTATUS_H
#define NOVATEL_OEM7_MSGS_MESSAGE_ACCESSSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace novatel_oem7_msgs
{
template <class ContainerAllocator>
struct AccessStatus_
{
  typedef AccessStatus_<ContainerAllocator> Type;

  AccessStatus_()
    : status(0)  {
    }
  AccessStatus_(const ContainerAllocator& _alloc)
    : status(0)  {
  (void)_alloc;
    }



   typedef uint32_t _status_type;
  _status_type status;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(DISABLE)
  #undef DISABLE
#endif
#if defined(_WIN32) && defined(ENABLE)
  #undef ENABLE
#endif

  enum {
    DISABLE = 0u,
    ENABLE = 1u,
  };


  typedef boost::shared_ptr< ::novatel_oem7_msgs::AccessStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::novatel_oem7_msgs::AccessStatus_<ContainerAllocator> const> ConstPtr;

}; // struct AccessStatus_

typedef ::novatel_oem7_msgs::AccessStatus_<std::allocator<void> > AccessStatus;

typedef boost::shared_ptr< ::novatel_oem7_msgs::AccessStatus > AccessStatusPtr;
typedef boost::shared_ptr< ::novatel_oem7_msgs::AccessStatus const> AccessStatusConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::novatel_oem7_msgs::AccessStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::novatel_oem7_msgs::AccessStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::novatel_oem7_msgs::AccessStatus_<ContainerAllocator1> & lhs, const ::novatel_oem7_msgs::AccessStatus_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::novatel_oem7_msgs::AccessStatus_<ContainerAllocator1> & lhs, const ::novatel_oem7_msgs::AccessStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace novatel_oem7_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::novatel_oem7_msgs::AccessStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::novatel_oem7_msgs::AccessStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::novatel_oem7_msgs::AccessStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::novatel_oem7_msgs::AccessStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::novatel_oem7_msgs::AccessStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::novatel_oem7_msgs::AccessStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::novatel_oem7_msgs::AccessStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2cd4f15e52faa2d78b49e438ede76437";
  }

  static const char* value(const ::novatel_oem7_msgs::AccessStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2cd4f15e52faa2d7ULL;
  static const uint64_t static_value2 = 0x8b49e438ede76437ULL;
};

template<class ContainerAllocator>
struct DataType< ::novatel_oem7_msgs::AccessStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "novatel_oem7_msgs/AccessStatus";
  }

  static const char* value(const ::novatel_oem7_msgs::AccessStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::novatel_oem7_msgs::AccessStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 DISABLE  = 0\n"
"uint32 ENABLE   = 1\n"
"\n"
"\n"
"uint32 status\n"
;
  }

  static const char* value(const ::novatel_oem7_msgs::AccessStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::novatel_oem7_msgs::AccessStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AccessStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::novatel_oem7_msgs::AccessStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::novatel_oem7_msgs::AccessStatus_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NOVATEL_OEM7_MSGS_MESSAGE_ACCESSSTATUS_H
