// Generated by gencpp from file novatel_oem7_msgs/IMURATECORRIMU.msg
// DO NOT EDIT!


#ifndef NOVATEL_OEM7_MSGS_MESSAGE_IMURATECORRIMU_H
#define NOVATEL_OEM7_MSGS_MESSAGE_IMURATECORRIMU_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <novatel_oem7_msgs/Oem7Header.h>

namespace novatel_oem7_msgs
{
template <class ContainerAllocator>
struct IMURATECORRIMU_
{
  typedef IMURATECORRIMU_<ContainerAllocator> Type;

  IMURATECORRIMU_()
    : header()
    , nov_header()
    , week(0)
    , seconds(0.0)
    , pitch_rate(0.0)
    , roll_rate(0.0)
    , yaw_rate(0.0)
    , lateral_acc(0.0)
    , longitudinal_acc(0.0)
    , vertical_acc(0.0)  {
    }
  IMURATECORRIMU_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , nov_header(_alloc)
    , week(0)
    , seconds(0.0)
    , pitch_rate(0.0)
    , roll_rate(0.0)
    , yaw_rate(0.0)
    , lateral_acc(0.0)
    , longitudinal_acc(0.0)
    , vertical_acc(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::novatel_oem7_msgs::Oem7Header_<ContainerAllocator>  _nov_header_type;
  _nov_header_type nov_header;

   typedef uint32_t _week_type;
  _week_type week;

   typedef double _seconds_type;
  _seconds_type seconds;

   typedef double _pitch_rate_type;
  _pitch_rate_type pitch_rate;

   typedef double _roll_rate_type;
  _roll_rate_type roll_rate;

   typedef double _yaw_rate_type;
  _yaw_rate_type yaw_rate;

   typedef double _lateral_acc_type;
  _lateral_acc_type lateral_acc;

   typedef double _longitudinal_acc_type;
  _longitudinal_acc_type longitudinal_acc;

   typedef double _vertical_acc_type;
  _vertical_acc_type vertical_acc;





  typedef boost::shared_ptr< ::novatel_oem7_msgs::IMURATECORRIMU_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::novatel_oem7_msgs::IMURATECORRIMU_<ContainerAllocator> const> ConstPtr;

}; // struct IMURATECORRIMU_

typedef ::novatel_oem7_msgs::IMURATECORRIMU_<std::allocator<void> > IMURATECORRIMU;

typedef boost::shared_ptr< ::novatel_oem7_msgs::IMURATECORRIMU > IMURATECORRIMUPtr;
typedef boost::shared_ptr< ::novatel_oem7_msgs::IMURATECORRIMU const> IMURATECORRIMUConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::novatel_oem7_msgs::IMURATECORRIMU_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::novatel_oem7_msgs::IMURATECORRIMU_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::novatel_oem7_msgs::IMURATECORRIMU_<ContainerAllocator1> & lhs, const ::novatel_oem7_msgs::IMURATECORRIMU_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.nov_header == rhs.nov_header &&
    lhs.week == rhs.week &&
    lhs.seconds == rhs.seconds &&
    lhs.pitch_rate == rhs.pitch_rate &&
    lhs.roll_rate == rhs.roll_rate &&
    lhs.yaw_rate == rhs.yaw_rate &&
    lhs.lateral_acc == rhs.lateral_acc &&
    lhs.longitudinal_acc == rhs.longitudinal_acc &&
    lhs.vertical_acc == rhs.vertical_acc;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::novatel_oem7_msgs::IMURATECORRIMU_<ContainerAllocator1> & lhs, const ::novatel_oem7_msgs::IMURATECORRIMU_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace novatel_oem7_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::novatel_oem7_msgs::IMURATECORRIMU_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::novatel_oem7_msgs::IMURATECORRIMU_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::novatel_oem7_msgs::IMURATECORRIMU_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::novatel_oem7_msgs::IMURATECORRIMU_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::novatel_oem7_msgs::IMURATECORRIMU_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::novatel_oem7_msgs::IMURATECORRIMU_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::novatel_oem7_msgs::IMURATECORRIMU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "80f9943a9481de2464fd83884670e360";
  }

  static const char* value(const ::novatel_oem7_msgs::IMURATECORRIMU_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x80f9943a9481de24ULL;
  static const uint64_t static_value2 = 0x64fd83884670e360ULL;
};

template<class ContainerAllocator>
struct DataType< ::novatel_oem7_msgs::IMURATECORRIMU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "novatel_oem7_msgs/IMURATECORRIMU";
  }

  static const char* value(const ::novatel_oem7_msgs::IMURATECORRIMU_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::novatel_oem7_msgs::IMURATECORRIMU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header           header\n"
"Oem7Header       nov_header\n"
"uint32           week\n"
"float64          seconds\n"
"float64          pitch_rate\n"
"float64          roll_rate\n"
"float64          yaw_rate\n"
"float64          lateral_acc\n"
"float64          longitudinal_acc\n"
"float64          vertical_acc\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: novatel_oem7_msgs/Oem7Header\n"
"uint16 OEM7MSGTYPE_LOG =  0\n"
"\n"
"\n"
"string message_name\n"
"uint16 message_id\n"
"uint8  message_type\n"
"uint32 sequence_number\n"
"uint8  time_status\n"
"uint16 gps_week_number\n"
"uint32 gps_week_milliseconds\n"
"\n"
;
  }

  static const char* value(const ::novatel_oem7_msgs::IMURATECORRIMU_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::novatel_oem7_msgs::IMURATECORRIMU_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.nov_header);
      stream.next(m.week);
      stream.next(m.seconds);
      stream.next(m.pitch_rate);
      stream.next(m.roll_rate);
      stream.next(m.yaw_rate);
      stream.next(m.lateral_acc);
      stream.next(m.longitudinal_acc);
      stream.next(m.vertical_acc);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IMURATECORRIMU_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::novatel_oem7_msgs::IMURATECORRIMU_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::novatel_oem7_msgs::IMURATECORRIMU_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "nov_header: ";
    s << std::endl;
    Printer< ::novatel_oem7_msgs::Oem7Header_<ContainerAllocator> >::stream(s, indent + "  ", v.nov_header);
    s << indent << "week: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.week);
    s << indent << "seconds: ";
    Printer<double>::stream(s, indent + "  ", v.seconds);
    s << indent << "pitch_rate: ";
    Printer<double>::stream(s, indent + "  ", v.pitch_rate);
    s << indent << "roll_rate: ";
    Printer<double>::stream(s, indent + "  ", v.roll_rate);
    s << indent << "yaw_rate: ";
    Printer<double>::stream(s, indent + "  ", v.yaw_rate);
    s << indent << "lateral_acc: ";
    Printer<double>::stream(s, indent + "  ", v.lateral_acc);
    s << indent << "longitudinal_acc: ";
    Printer<double>::stream(s, indent + "  ", v.longitudinal_acc);
    s << indent << "vertical_acc: ";
    Printer<double>::stream(s, indent + "  ", v.vertical_acc);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NOVATEL_OEM7_MSGS_MESSAGE_IMURATECORRIMU_H
