// Generated by gencpp from file novatel_oem7_msgs/InertialSolutionStatus.msg
// DO NOT EDIT!


#ifndef NOVATEL_OEM7_MSGS_MESSAGE_INERTIALSOLUTIONSTATUS_H
#define NOVATEL_OEM7_MSGS_MESSAGE_INERTIALSOLUTIONSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace novatel_oem7_msgs
{
template <class ContainerAllocator>
struct InertialSolutionStatus_
{
  typedef InertialSolutionStatus_<ContainerAllocator> Type;

  InertialSolutionStatus_()
    : status(0)  {
    }
  InertialSolutionStatus_(const ContainerAllocator& _alloc)
    : status(0)  {
  (void)_alloc;
    }



   typedef uint32_t _status_type;
  _status_type status;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(INS_INACTIVE)
  #undef INS_INACTIVE
#endif
#if defined(_WIN32) && defined(INS_ALIGNING)
  #undef INS_ALIGNING
#endif
#if defined(_WIN32) && defined(INS_HIGH_VARIANCE)
  #undef INS_HIGH_VARIANCE
#endif
#if defined(_WIN32) && defined(INS_SOLUTION_GOOD)
  #undef INS_SOLUTION_GOOD
#endif
#if defined(_WIN32) && defined(INS_SOLUTION_FREE)
  #undef INS_SOLUTION_FREE
#endif
#if defined(_WIN32) && defined(INS_ALIGNMENT_COMPLETE)
  #undef INS_ALIGNMENT_COMPLETE
#endif
#if defined(_WIN32) && defined(DETERMINING_ORIENTATION)
  #undef DETERMINING_ORIENTATION
#endif
#if defined(_WIN32) && defined(WAITING_INITIAL_POS)
  #undef WAITING_INITIAL_POS
#endif
#if defined(_WIN32) && defined(WAITING_AZIMUTH)
  #undef WAITING_AZIMUTH
#endif
#if defined(_WIN32) && defined(INITIALIZING_BIASES)
  #undef INITIALIZING_BIASES
#endif
#if defined(_WIN32) && defined(MOTION_DETECT)
  #undef MOTION_DETECT
#endif

  enum {
    INS_INACTIVE = 0u,
    INS_ALIGNING = 1u,
    INS_HIGH_VARIANCE = 2u,
    INS_SOLUTION_GOOD = 3u,
    INS_SOLUTION_FREE = 6u,
    INS_ALIGNMENT_COMPLETE = 7u,
    DETERMINING_ORIENTATION = 8u,
    WAITING_INITIAL_POS = 9u,
    WAITING_AZIMUTH = 10u,
    INITIALIZING_BIASES = 11u,
    MOTION_DETECT = 12u,
  };


  typedef boost::shared_ptr< ::novatel_oem7_msgs::InertialSolutionStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::novatel_oem7_msgs::InertialSolutionStatus_<ContainerAllocator> const> ConstPtr;

}; // struct InertialSolutionStatus_

typedef ::novatel_oem7_msgs::InertialSolutionStatus_<std::allocator<void> > InertialSolutionStatus;

typedef boost::shared_ptr< ::novatel_oem7_msgs::InertialSolutionStatus > InertialSolutionStatusPtr;
typedef boost::shared_ptr< ::novatel_oem7_msgs::InertialSolutionStatus const> InertialSolutionStatusConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::novatel_oem7_msgs::InertialSolutionStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::novatel_oem7_msgs::InertialSolutionStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::novatel_oem7_msgs::InertialSolutionStatus_<ContainerAllocator1> & lhs, const ::novatel_oem7_msgs::InertialSolutionStatus_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::novatel_oem7_msgs::InertialSolutionStatus_<ContainerAllocator1> & lhs, const ::novatel_oem7_msgs::InertialSolutionStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace novatel_oem7_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::novatel_oem7_msgs::InertialSolutionStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::novatel_oem7_msgs::InertialSolutionStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::novatel_oem7_msgs::InertialSolutionStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::novatel_oem7_msgs::InertialSolutionStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::novatel_oem7_msgs::InertialSolutionStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::novatel_oem7_msgs::InertialSolutionStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::novatel_oem7_msgs::InertialSolutionStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e6e451c61d52151bd82b333d8be963d5";
  }

  static const char* value(const ::novatel_oem7_msgs::InertialSolutionStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe6e451c61d52151bULL;
  static const uint64_t static_value2 = 0xd82b333d8be963d5ULL;
};

template<class ContainerAllocator>
struct DataType< ::novatel_oem7_msgs::InertialSolutionStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "novatel_oem7_msgs/InertialSolutionStatus";
  }

  static const char* value(const ::novatel_oem7_msgs::InertialSolutionStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::novatel_oem7_msgs::InertialSolutionStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"uint32 INS_INACTIVE            =  0\n"
"uint32 INS_ALIGNING            =  1\n"
"uint32 INS_HIGH_VARIANCE       =  2\n"
"uint32 INS_SOLUTION_GOOD       =  3\n"
"uint32 INS_SOLUTION_FREE       =  6\n"
"uint32 INS_ALIGNMENT_COMPLETE  =  7\n"
"uint32 DETERMINING_ORIENTATION =  8\n"
"uint32 WAITING_INITIAL_POS     =  9\n"
"uint32 WAITING_AZIMUTH         = 10\n"
"uint32 INITIALIZING_BIASES     = 11\n"
"uint32 MOTION_DETECT           = 12\n"
"\n"
"uint32 status\n"
;
  }

  static const char* value(const ::novatel_oem7_msgs::InertialSolutionStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::novatel_oem7_msgs::InertialSolutionStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InertialSolutionStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::novatel_oem7_msgs::InertialSolutionStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::novatel_oem7_msgs::InertialSolutionStatus_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NOVATEL_OEM7_MSGS_MESSAGE_INERTIALSOLUTIONSTATUS_H
