// Generated by gencpp from file novatel_oem7_msgs/Oem7AbasciiCmdResponse.msg
// DO NOT EDIT!


#ifndef NOVATEL_OEM7_MSGS_MESSAGE_OEM7ABASCIICMDRESPONSE_H
#define NOVATEL_OEM7_MSGS_MESSAGE_OEM7ABASCIICMDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace novatel_oem7_msgs
{
template <class ContainerAllocator>
struct Oem7AbasciiCmdResponse_
{
  typedef Oem7AbasciiCmdResponse_<ContainerAllocator> Type;

  Oem7AbasciiCmdResponse_()
    : rsp()  {
    }
  Oem7AbasciiCmdResponse_(const ContainerAllocator& _alloc)
    : rsp(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _rsp_type;
  _rsp_type rsp;





  typedef boost::shared_ptr< ::novatel_oem7_msgs::Oem7AbasciiCmdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::novatel_oem7_msgs::Oem7AbasciiCmdResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Oem7AbasciiCmdResponse_

typedef ::novatel_oem7_msgs::Oem7AbasciiCmdResponse_<std::allocator<void> > Oem7AbasciiCmdResponse;

typedef boost::shared_ptr< ::novatel_oem7_msgs::Oem7AbasciiCmdResponse > Oem7AbasciiCmdResponsePtr;
typedef boost::shared_ptr< ::novatel_oem7_msgs::Oem7AbasciiCmdResponse const> Oem7AbasciiCmdResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::novatel_oem7_msgs::Oem7AbasciiCmdResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::novatel_oem7_msgs::Oem7AbasciiCmdResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::novatel_oem7_msgs::Oem7AbasciiCmdResponse_<ContainerAllocator1> & lhs, const ::novatel_oem7_msgs::Oem7AbasciiCmdResponse_<ContainerAllocator2> & rhs)
{
  return lhs.rsp == rhs.rsp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::novatel_oem7_msgs::Oem7AbasciiCmdResponse_<ContainerAllocator1> & lhs, const ::novatel_oem7_msgs::Oem7AbasciiCmdResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace novatel_oem7_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::novatel_oem7_msgs::Oem7AbasciiCmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::novatel_oem7_msgs::Oem7AbasciiCmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::novatel_oem7_msgs::Oem7AbasciiCmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::novatel_oem7_msgs::Oem7AbasciiCmdResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::novatel_oem7_msgs::Oem7AbasciiCmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::novatel_oem7_msgs::Oem7AbasciiCmdResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::novatel_oem7_msgs::Oem7AbasciiCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "79bdb3430fb54824bdb535b425813cdc";
  }

  static const char* value(const ::novatel_oem7_msgs::Oem7AbasciiCmdResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x79bdb3430fb54824ULL;
  static const uint64_t static_value2 = 0xbdb535b425813cdcULL;
};

template<class ContainerAllocator>
struct DataType< ::novatel_oem7_msgs::Oem7AbasciiCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "novatel_oem7_msgs/Oem7AbasciiCmdResponse";
  }

  static const char* value(const ::novatel_oem7_msgs::Oem7AbasciiCmdResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::novatel_oem7_msgs::Oem7AbasciiCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string rsp\n"
"\n"
"\n"
;
  }

  static const char* value(const ::novatel_oem7_msgs::Oem7AbasciiCmdResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::novatel_oem7_msgs::Oem7AbasciiCmdResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rsp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Oem7AbasciiCmdResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::novatel_oem7_msgs::Oem7AbasciiCmdResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::novatel_oem7_msgs::Oem7AbasciiCmdResponse_<ContainerAllocator>& v)
  {
    s << indent << "rsp: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.rsp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NOVATEL_OEM7_MSGS_MESSAGE_OEM7ABASCIICMDRESPONSE_H
