// Generated by gencpp from file novatel_oem7_msgs/PPPPOS.msg
// DO NOT EDIT!


#ifndef NOVATEL_OEM7_MSGS_MESSAGE_PPPPOS_H
#define NOVATEL_OEM7_MSGS_MESSAGE_PPPPOS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <novatel_oem7_msgs/Oem7Header.h>
#include <novatel_oem7_msgs/SolutionStatus.h>
#include <novatel_oem7_msgs/PositionOrVelocityType.h>
#include <novatel_oem7_msgs/BestExtendedSolutionStatus.h>

namespace novatel_oem7_msgs
{
template <class ContainerAllocator>
struct PPPPOS_
{
  typedef PPPPOS_<ContainerAllocator> Type;

  PPPPOS_()
    : header()
    , nov_header()
    , sol_status()
    , pos_type()
    , lat(0.0)
    , lon(0.0)
    , hgt(0.0)
    , undulation(0.0)
    , datum_id(0)
    , lat_stdev(0.0)
    , lon_stdev(0.0)
    , hgt_stdev(0.0)
    , stn_id()
    , diff_age(0.0)
    , sol_age(0.0)
    , num_svs(0)
    , num_sol_svs(0)
    , num_sol_l1_svs(0)
    , num_sol_multi_svs(0)
    , reserved(0)
    , ext_sol_stat()
    , reserved2(0)
    , gps_glonass_sig_mask(0)  {
    }
  PPPPOS_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , nov_header(_alloc)
    , sol_status(_alloc)
    , pos_type(_alloc)
    , lat(0.0)
    , lon(0.0)
    , hgt(0.0)
    , undulation(0.0)
    , datum_id(0)
    , lat_stdev(0.0)
    , lon_stdev(0.0)
    , hgt_stdev(0.0)
    , stn_id(_alloc)
    , diff_age(0.0)
    , sol_age(0.0)
    , num_svs(0)
    , num_sol_svs(0)
    , num_sol_l1_svs(0)
    , num_sol_multi_svs(0)
    , reserved(0)
    , ext_sol_stat(_alloc)
    , reserved2(0)
    , gps_glonass_sig_mask(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::novatel_oem7_msgs::Oem7Header_<ContainerAllocator>  _nov_header_type;
  _nov_header_type nov_header;

   typedef  ::novatel_oem7_msgs::SolutionStatus_<ContainerAllocator>  _sol_status_type;
  _sol_status_type sol_status;

   typedef  ::novatel_oem7_msgs::PositionOrVelocityType_<ContainerAllocator>  _pos_type_type;
  _pos_type_type pos_type;

   typedef double _lat_type;
  _lat_type lat;

   typedef double _lon_type;
  _lon_type lon;

   typedef double _hgt_type;
  _hgt_type hgt;

   typedef float _undulation_type;
  _undulation_type undulation;

   typedef uint32_t _datum_id_type;
  _datum_id_type datum_id;

   typedef float _lat_stdev_type;
  _lat_stdev_type lat_stdev;

   typedef float _lon_stdev_type;
  _lon_stdev_type lon_stdev;

   typedef float _hgt_stdev_type;
  _hgt_stdev_type hgt_stdev;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _stn_id_type;
  _stn_id_type stn_id;

   typedef float _diff_age_type;
  _diff_age_type diff_age;

   typedef float _sol_age_type;
  _sol_age_type sol_age;

   typedef uint8_t _num_svs_type;
  _num_svs_type num_svs;

   typedef uint8_t _num_sol_svs_type;
  _num_sol_svs_type num_sol_svs;

   typedef uint8_t _num_sol_l1_svs_type;
  _num_sol_l1_svs_type num_sol_l1_svs;

   typedef uint8_t _num_sol_multi_svs_type;
  _num_sol_multi_svs_type num_sol_multi_svs;

   typedef uint8_t _reserved_type;
  _reserved_type reserved;

   typedef  ::novatel_oem7_msgs::BestExtendedSolutionStatus_<ContainerAllocator>  _ext_sol_stat_type;
  _ext_sol_stat_type ext_sol_stat;

   typedef uint8_t _reserved2_type;
  _reserved2_type reserved2;

   typedef uint8_t _gps_glonass_sig_mask_type;
  _gps_glonass_sig_mask_type gps_glonass_sig_mask;





  typedef boost::shared_ptr< ::novatel_oem7_msgs::PPPPOS_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::novatel_oem7_msgs::PPPPOS_<ContainerAllocator> const> ConstPtr;

}; // struct PPPPOS_

typedef ::novatel_oem7_msgs::PPPPOS_<std::allocator<void> > PPPPOS;

typedef boost::shared_ptr< ::novatel_oem7_msgs::PPPPOS > PPPPOSPtr;
typedef boost::shared_ptr< ::novatel_oem7_msgs::PPPPOS const> PPPPOSConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::novatel_oem7_msgs::PPPPOS_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::novatel_oem7_msgs::PPPPOS_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::novatel_oem7_msgs::PPPPOS_<ContainerAllocator1> & lhs, const ::novatel_oem7_msgs::PPPPOS_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.nov_header == rhs.nov_header &&
    lhs.sol_status == rhs.sol_status &&
    lhs.pos_type == rhs.pos_type &&
    lhs.lat == rhs.lat &&
    lhs.lon == rhs.lon &&
    lhs.hgt == rhs.hgt &&
    lhs.undulation == rhs.undulation &&
    lhs.datum_id == rhs.datum_id &&
    lhs.lat_stdev == rhs.lat_stdev &&
    lhs.lon_stdev == rhs.lon_stdev &&
    lhs.hgt_stdev == rhs.hgt_stdev &&
    lhs.stn_id == rhs.stn_id &&
    lhs.diff_age == rhs.diff_age &&
    lhs.sol_age == rhs.sol_age &&
    lhs.num_svs == rhs.num_svs &&
    lhs.num_sol_svs == rhs.num_sol_svs &&
    lhs.num_sol_l1_svs == rhs.num_sol_l1_svs &&
    lhs.num_sol_multi_svs == rhs.num_sol_multi_svs &&
    lhs.reserved == rhs.reserved &&
    lhs.ext_sol_stat == rhs.ext_sol_stat &&
    lhs.reserved2 == rhs.reserved2 &&
    lhs.gps_glonass_sig_mask == rhs.gps_glonass_sig_mask;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::novatel_oem7_msgs::PPPPOS_<ContainerAllocator1> & lhs, const ::novatel_oem7_msgs::PPPPOS_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace novatel_oem7_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::novatel_oem7_msgs::PPPPOS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::novatel_oem7_msgs::PPPPOS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::novatel_oem7_msgs::PPPPOS_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::novatel_oem7_msgs::PPPPOS_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::novatel_oem7_msgs::PPPPOS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::novatel_oem7_msgs::PPPPOS_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::novatel_oem7_msgs::PPPPOS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f4f8223844674080be04b6440d9a0547";
  }

  static const char* value(const ::novatel_oem7_msgs::PPPPOS_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf4f8223844674080ULL;
  static const uint64_t static_value2 = 0xbe04b6440d9a0547ULL;
};

template<class ContainerAllocator>
struct DataType< ::novatel_oem7_msgs::PPPPOS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "novatel_oem7_msgs/PPPPOS";
  }

  static const char* value(const ::novatel_oem7_msgs::PPPPOS_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::novatel_oem7_msgs::PPPPOS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header                          header\n"
"Oem7Header                      nov_header\n"
"SolutionStatus                  sol_status\n"
"PositionOrVelocityType          pos_type\n"
"float64                         lat\n"
"float64                         lon\n"
"float64                         hgt\n"
"float32                         undulation\n"
"uint32                          datum_id\n"
"float32                         lat_stdev\n"
"float32                         lon_stdev\n"
"float32                         hgt_stdev\n"
"string                          stn_id\n"
"float32                         diff_age\n"
"float32                         sol_age\n"
"uint8                           num_svs\n"
"uint8                           num_sol_svs\n"
"uint8                           num_sol_l1_svs\n"
"uint8                           num_sol_multi_svs\n"
"uint8                           reserved\n"
"BestExtendedSolutionStatus      ext_sol_stat\n"
"uint8                           reserved2\n"
"uint8                           gps_glonass_sig_mask\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: novatel_oem7_msgs/Oem7Header\n"
"uint16 OEM7MSGTYPE_LOG =  0\n"
"\n"
"\n"
"string message_name\n"
"uint16 message_id\n"
"uint8  message_type\n"
"uint32 sequence_number\n"
"uint8  time_status\n"
"uint16 gps_week_number\n"
"uint32 gps_week_milliseconds\n"
"\n"
"\n"
"================================================================================\n"
"MSG: novatel_oem7_msgs/SolutionStatus\n"
"uint32 SOL_COMPUTED             = 0\n"
"uint32 INSUFFICIENT_OBS         = 1\n"
"uint32 NO_CONVERGENCE            = 2\n"
"uint32 SINGULARITY              = 3\n"
"uint32 COV_TRACE                = 4\n"
"uint32 TEST_DIST                = 5\n"
"uint32 COLD_START               = 6\n"
"uint32 V_H_LIMIT                = 7\n"
"uint32 VARIANCE                 = 8\n"
"uint32 RESIDUALS                = 9\n"
"uint32 INTEGRITY_WARNING        = 13\n"
"uint32 PENDING                  = 18\n"
"uint32 INVALID_FIX              = 19\n"
"uint32 UNAUTHORIZED             = 20\n"
"uint32 INVALID_RATE             = 22\n"
"\n"
"uint32 status\n"
"\n"
"================================================================================\n"
"MSG: novatel_oem7_msgs/PositionOrVelocityType\n"
"uint32 NONE                     = 0\n"
"uint32 FIXEDPOS                 = 1\n"
"uint32 FIXEDHEIGHT              = 2\n"
"uint32 DOPPLER_VELOCITY         = 8\n"
"uint32 SINGLE                   = 16\n"
"uint32 PSRDIFF                  = 17\n"
"uint32 WAAS                     = 18\n"
"uint32 PROPAGATED               = 19\n"
"uint32 L1_FLOAT                 = 32\n"
"uint32 NARROW_FLOAT             = 34\n"
"uint32 L1_INT                   = 48\n"
"uint32 WIDE_INT                 = 49\n"
"uint32 NARROW_INT               = 50\n"
"uint32 RTK_DIRECT_INS           = 51\n"
"uint32 INS_SBAS                 = 52\n"
"uint32 INS_PSRSP                = 53\n"
"uint32 INS_PSRDIFF              = 54\n"
"uint32 INS_RTKFLOAT             = 55\n"
"uint32 INS_RTKFIXED             = 56\n"
"uint32 PPP_CONVERGING           = 68\n"
"uint32 PPP                      = 69\n"
"uint32 OPERATIONAL              = 70\n"
"uint32 WARNING                  = 71\n"
"uint32 OUT_OF_BOUNDS            = 72\n"
"uint32 INS_PPP_CONVERGING       = 73\n"
"uint32 INS_PPP                  = 74\n"
"uint32 PPP_BASIC_CONVERGING     = 77\n"
"uint32 PPP_BASIC                = 78\n"
"uint32 INS_PPP_BASIC_CONVERGING = 79\n"
"uint32 INS_PPP_BASIC            = 80\n"
"\n"
"\n"
"uint32 type\n"
"================================================================================\n"
"MSG: novatel_oem7_msgs/BestExtendedSolutionStatus\n"
"# Bit 0\n"
"uint8 RTK_SOLUTION_VERIFIED = 1\n"
"uint8 PDP_SOLUTION_IS_GLIDE = 1\n"
"\n"
"# Bits 1-3, mask 0xE\n"
"uint8 KLOBUCHAR_BROADCAST                =  2 # 0x2 \n"
"uint8 SBAS_BROADCAST                     =  4 # 0x4 \n"
"uint8 MULTI_FREQUENCY_COMPUTED           =  6 # 0x6\n"
"uint8 PSRDIFF_CORRECTION                 =  8 # 0x8\n"
"uint8 NOVATEL_BLENDED_IONO_VALUE         = 10 #0xA\n"
"\n"
"# Bit 4\n"
"uint8 RTK_ASSIST_ACTIVE = 16 # 0x10\n"
"\n"
"# Bit 5\n"
"uint8 ANTENNA_INFORMATION_IS_MISSING = 32 # 0x20\n"
"\n"
"# Bit 6 reserved\n"
"uint8 RESERVED = 64 # 0x40\n"
"\n"
"# Bit 7\n"
"uint8 POSITION_INCLUDES_TERRAIN_COMPENSATION_CORRECTIONS = 128 # 0x80\n"
"\n"
"\n"
"\n"
"uint8 status\n"
;
  }

  static const char* value(const ::novatel_oem7_msgs::PPPPOS_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::novatel_oem7_msgs::PPPPOS_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.nov_header);
      stream.next(m.sol_status);
      stream.next(m.pos_type);
      stream.next(m.lat);
      stream.next(m.lon);
      stream.next(m.hgt);
      stream.next(m.undulation);
      stream.next(m.datum_id);
      stream.next(m.lat_stdev);
      stream.next(m.lon_stdev);
      stream.next(m.hgt_stdev);
      stream.next(m.stn_id);
      stream.next(m.diff_age);
      stream.next(m.sol_age);
      stream.next(m.num_svs);
      stream.next(m.num_sol_svs);
      stream.next(m.num_sol_l1_svs);
      stream.next(m.num_sol_multi_svs);
      stream.next(m.reserved);
      stream.next(m.ext_sol_stat);
      stream.next(m.reserved2);
      stream.next(m.gps_glonass_sig_mask);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PPPPOS_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::novatel_oem7_msgs::PPPPOS_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::novatel_oem7_msgs::PPPPOS_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "nov_header: ";
    s << std::endl;
    Printer< ::novatel_oem7_msgs::Oem7Header_<ContainerAllocator> >::stream(s, indent + "  ", v.nov_header);
    s << indent << "sol_status: ";
    s << std::endl;
    Printer< ::novatel_oem7_msgs::SolutionStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.sol_status);
    s << indent << "pos_type: ";
    s << std::endl;
    Printer< ::novatel_oem7_msgs::PositionOrVelocityType_<ContainerAllocator> >::stream(s, indent + "  ", v.pos_type);
    s << indent << "lat: ";
    Printer<double>::stream(s, indent + "  ", v.lat);
    s << indent << "lon: ";
    Printer<double>::stream(s, indent + "  ", v.lon);
    s << indent << "hgt: ";
    Printer<double>::stream(s, indent + "  ", v.hgt);
    s << indent << "undulation: ";
    Printer<float>::stream(s, indent + "  ", v.undulation);
    s << indent << "datum_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.datum_id);
    s << indent << "lat_stdev: ";
    Printer<float>::stream(s, indent + "  ", v.lat_stdev);
    s << indent << "lon_stdev: ";
    Printer<float>::stream(s, indent + "  ", v.lon_stdev);
    s << indent << "hgt_stdev: ";
    Printer<float>::stream(s, indent + "  ", v.hgt_stdev);
    s << indent << "stn_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.stn_id);
    s << indent << "diff_age: ";
    Printer<float>::stream(s, indent + "  ", v.diff_age);
    s << indent << "sol_age: ";
    Printer<float>::stream(s, indent + "  ", v.sol_age);
    s << indent << "num_svs: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.num_svs);
    s << indent << "num_sol_svs: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.num_sol_svs);
    s << indent << "num_sol_l1_svs: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.num_sol_l1_svs);
    s << indent << "num_sol_multi_svs: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.num_sol_multi_svs);
    s << indent << "reserved: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reserved);
    s << indent << "ext_sol_stat: ";
    s << std::endl;
    Printer< ::novatel_oem7_msgs::BestExtendedSolutionStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.ext_sol_stat);
    s << indent << "reserved2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reserved2);
    s << indent << "gps_glonass_sig_mask: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gps_glonass_sig_mask);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NOVATEL_OEM7_MSGS_MESSAGE_PPPPOS_H
